title: Welcome to What A Simple Dash!
defaultColumns: 4
theme:
  mainBackground: 'rgba(17, 24, 39, 1)'
  titleBackground: 'rgba(0, 0, 0, 0.4)'
  text: 'rgba(255, 255, 255, 1)'
  serviceBackground: 'rgba(22, 27, 34, 1)'
  serviceBackgroundHover: 'rgba(33, 38, 45, 1)'
settings:
  showTitleBackgrounds: true
  backgroundBlur: 0
backgrounds:
  active: ''
  history: []
widgets:
  columns: 2
  items:
    - name: Clock
      type: clock
      timeZone: "America/New_York"
      format: "12h"
    - name: Weather
      type: weather
      provider: openweathermap
      location: "New York"
      apiKey: "YOUR_OPENWEATHERMAP_API_KEY"
      units: "imperial"
groups:
  - name: Getting Started
    columns: 4
    services:
      - name: Edit This File!
        subtitle: Edit config/services.yml to start
        url: https://github.com/leraptor65/whatasimpledash
        icon: FaWrench
      - name: My GitHub
        subtitle: Visit the project repo
        url: https://github.com/leraptor65/whatasimpledash
        icon: FaGithub
        ping: https://github.com/leraptor65/whatasimpledash