services:
  whatasimpledash:
    build: .
    image: leraptor65/whatasimpledash:local-build
    container_name: whatasimpledash-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./public/icons:/app/public/icons
      - ./public/backgrounds:/app/public/backgrounds
      - ./public/uploads:/app/public/uploads
