title: What A Simple Dash
defaultColumns: 3
theme:
  mainBackground: '#0e0e0e'
  titleBackground: rgba(0, 0, 0, .6)
  text: rgba(255, 255, 255, 1)
  serviceBackground: rgba(0, 0, 0, .6)
  serviceBackgroundHover: rgba(0, 0, 0, 1)
backgrounds:
  active: ''
  history: []
groups:
  - name: Productivity
    services:
      - name: GitHub
        url: https://github.com
        icon: github.png
      - name: Google
        url: https://google.com
        icon: google.png
    collapsed: false
  - name: Management
    services:
      - name: Dashboard Settings
        url: /settings
        icon: settings.png
    collapsed: false
settings:
  showTitleBackgrounds: true
  backgroundBlur: 6
  customGreeting: Welcome
  customHelpText: Let's Begin
  hideGreeting: false
  showGreetingBackground: true
  greetingRadius: 100
